name: HUBCore
main: fr.lemonadd.hubcore.Main
description: HUBCore
version: 1.0.0
author: LemonAdd
api-version: 1.15
commands:
  trails:
    description: Particules
  sethub:
    description: Set le spawn du Hub à votre position
  hub:
    description: Se téléporter au hub